apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
#            - mountPath: /docker-entrypoint-initdb.d
#              name: postgresinit
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
#        - name: postgresinit
#          persistentVolumeClaim:
#            claimName: postgresinit-pv-claim
